### PR TITLE
Add the ability to manually generate docs and post to GH pages

### PR DESCRIPTION
**Pull request by SeanTAllen**
For this PR to work the instructions for setup for GH pages need to
followed the first time after this is manually triggered.

Additionally, before triggering, a repository secret called RELEASE_TOKEN
needs to be set up. Access required for that token can be found in
the instructions at:

https://github.com/ponylang/library-documentation-action

### CODE REVIEW

**Comment by SeanTAllen** [comment]
Let me know if you don't know how to manually trigger this, I can show you after its merged.

**Comment by SeanTAllen** [comment]
actually, @ergl this isnt really a library is it? so this PR is kind of pointless and can be closed if its not.

**Comment by ergl** [comment]
@SeanTAllen it can be used as a library too, so having documentation is a nice addition!

**Comment by SeanTAllen** [comment]
Ah ok! Good to know.

**Pull request merged**
